name: Build and push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  TF_VERSION: "1.1.0"
  AWS_REGION: "eu-west-2"

jobs:
  menumaster:
    if: "!contains(github.event.commits[0].message, '[Bump version to]')"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: 'maven'

      - name: Maven settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "ghcr", "username": "statement2020", "password": "${{secrets.PACKAGE_SECRET}}" }]'
          githubServer: false
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: statement2020
          password: ${{ secrets.PACKAGE_SECRET }}
      - name: Build artefact
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ~/.m2/settings.xml
          mvn clean install -f ./asset-track/pom.xml
          mvn deploy -f ./asset-track/pom.xml
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
#  veridcheck-ui:
#    if: "!contains(github.event.commits[0].message, '[Bump version to]')"
#    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#      contents: read
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-node@v4
#        with:
#          java-version: '22'
#
#      - name: Build artefact
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          npm install grunt --save-dev
#          npm --prefix veridcheck-ui install
#          cd veridcheck-ui
#          npx grunt build
#
#      - name: Set up docker buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to GHCR
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        id: docker_build
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: veridcheck-ui/Dockerfile
#          push: true
#          tags: ghcr.io/veridcheck/veridcheck-ui:1.0.${{github.run_number}},ghcr.io/veridcheck/veridcheck-ui:latest